In [1]:
import requests
import json
from bs4 import BeautifulSoup as bs
import pandas as pd

In [17]:
url = input("Enter the URL of the page to scrape: ")
r = requests.get(url)
soup = bs(r.content)
json_fotmob = json.loads(soup.find('script', attrs={'id': '__NEXT_DATA__'}).contents[0])

In [18]:
# General match info
json_fotmob['props']['pageProps']['general']

{'matchId': '4756814',
 'matchName': 'Club Atletico Penarol-vs-San Antonio Bulo Bulo_Wed, Apr 9, 2025, 00:00 UTC',
 'matchRound': '2',
 'teamColors': {'darkMode': {'home': '#FCC300', 'away': '#04C2F8'},
  'lightMode': {'home': '#d6a200', 'away': '#00b1e6'},
  'fontDarkMode': {'home': 'rgba(29, 29, 29, 1.0)',
   'away': 'rgba(29, 29, 29, 1.0)'},
  'fontLightMode': {'home': 'rgba(255, 255, 255, 1.0)',
   'away': 'rgba(255, 255, 255, 1.0)'}},
 'leagueId': 898424,
 'leagueName': 'Copa Libertadores Grp. H',
 'leagueRoundName': '2',
 'parentLeagueId': 45,
 'countryCode': 'INT-2',
 'parentLeagueName': 'Copa Libertadores',
 'parentLeagueSeason': '2025',
 'parentLeagueTopScorerLink': 'https://data.fotmob.com/stats/45/season/25464/goals.json',
 'parentLeagueTournamentId': 25464,
 'homeTeam': {'name': 'Club Atletico Penarol', 'id': 8450},
 'awayTeam': {'name': 'San Antonio Bulo Bulo', 'id': 1297060},
 'coverageLevel': 'xG',
 'matchTimeUTC': 'Wed, Apr 9, 2025, 00:00 UTC',
 'matchTimeUTCDate': '2025-04-09T00:00:00.000Z',
 'started': True,
 'finished': True}

In [4]:
matchRound = int(json_fotmob['props']['pageProps']['general']['matchRound'])
matchRound

1

In [12]:
type(matchRound)

int

In [19]:
h_team = json_fotmob['props']['pageProps']['general']['homeTeam']['name']

In [6]:
json_fotmob['props']['pageProps']['general']['awayTeam']['name']

'Club Atletico Penarol'

In [20]:
df = pd.DataFrame(json_fotmob['props']['pageProps']['content']['playerStats'])
df

,71249,206724,211145,281238,282484,316023,338858,357184,363486,391991,...,1445403,1448091,1613127,1621219,1639717,1646996,1662516,1691290,1714925,1733285
name,Ivan Huayhuata,Camilo Mayada,Carlos Suarez,Maximiliano Olivera,Jose Penarrieta,Jorge Flores,Martin Campana,Rodrigo Vargas,Hector Villalba,Jaime Báez,...,Franco González,Nahuel Herrera,Leonardo Justiniano,Juan Rodriguez,Gustavo Mendoza,German Barbas,Huberth Sanchez,Sebastian Viveros,Leandro Umpierrez,Kevin Merida
id,71249,206724,211145,281238,282484,316023,338858,357184,363486,391991,...,1445403,1448091,1613127,1621219,1639717,1646996,1662516,1691290,1714925,1733285
optaId,178307,151890,169627,153116,148631,193390,78114,159180,122828,153448,...,609051,575486,501083,617160,644332,653827,502638,662044,624630,648701
teamId,1297060,8450,1297060,8450,1297060,1297060,8450,1297060,8450,8450,...,8450,8450,1297060,8450,1297060,8450,1297060,1297060,8450,1297060
teamName,San Antonio Bulo Bulo,Peñarol,San Antonio Bulo Bulo,Peñarol,San Antonio Bulo Bulo,San Antonio Bulo Bulo,Peñarol,San Antonio Bulo Bulo,Peñarol,Peñarol,...,Peñarol,Peñarol,San Antonio Bulo Bulo,Peñarol,San Antonio Bulo Bulo,Peñarol,San Antonio Bulo Bulo,San Antonio Bulo Bulo,Peñarol,San Antonio Bulo Bulo
isGoalkeeper,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
stats,[],[],"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...",[],"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...",[],"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...",...,[],"[{'title': 'Top stats', 'key': 'top_stats', 's...",[],[],"[{'title': 'Top stats', 'key': 'top_stats', 's...",[],"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...",[]
shotmap,[],[],"[{'id': 2798450493, 'eventType': 'AttemptSaved...","[{'id': 2798441949, 'eventType': 'AttemptSaved...",[],"[{'id': 2798466685, 'eventType': 'Miss', 'team...",[],[],"[{'id': 2798459929, 'eventType': 'AttemptSaved...","[{'id': 2798458169, 'eventType': 'Miss', 'team...",...,[],[],[],[],[],[],[],[],[],[]
funFacts,[],[],[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],[]

In [21]:
df = df.T
df.head()

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shotmap,funFacts
71249,Ivan Huayhuata,71249,178307,1297060,San Antonio Bulo Bulo,False,[],[],[]
206724,Camilo Mayada,206724,151890,8450,Peñarol,False,[],[],[]
211145,Carlos Suarez,211145,169627,1297060,San Antonio Bulo Bulo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798450493, 'eventType': 'AttemptSaved...",[]
281238,Maximiliano Olivera,281238,153116,8450,Peñarol,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798441949, 'eventType': 'AttemptSaved...",[]
282484,Jose Penarrieta,282484,148631,1297060,San Antonio Bulo Bulo,True,[],[],[]

In [22]:
df['player_id'] = df.index
df.reset_index(drop=True, inplace=True)
df.head()

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shotmap,funFacts,player_id
0,Ivan Huayhuata,71249,178307,1297060,San Antonio Bulo Bulo,False,[],[],[],71249
1,Camilo Mayada,206724,151890,8450,Peñarol,False,[],[],[],206724
2,Carlos Suarez,211145,169627,1297060,San Antonio Bulo Bulo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798450493, 'eventType': 'AttemptSaved...",[],211145
3,Maximiliano Olivera,281238,153116,8450,Peñarol,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798441949, 'eventType': 'AttemptSaved...",[],281238
4,Jose Penarrieta,282484,148631,1297060,San Antonio Bulo Bulo,True,[],[],[],282484

In [23]:
new_df = df[['teamName', 'player_id']].copy()
new_df

                 teamName player_id
0   San Antonio Bulo Bulo     71249
1                 Peñarol    206724
2   San Antonio Bulo Bulo    211145
3                 Peñarol    281238
4   San Antonio Bulo Bulo    282484
5   San Antonio Bulo Bulo    316023
6                 Peñarol    338858
7   San Antonio Bulo Bulo    357184
8                 Peñarol    363486
9                 Peñarol    391991
10                Peñarol    398197
11                Peñarol    495321
12                Peñarol    642763
13                Peñarol    645841
14  San Antonio Bulo Bulo    681451
15  San Antonio Bulo Bulo    683969
16                Peñarol    738100
17                Peñarol    812758
18                Peñarol    834965
19  San Antonio Bulo Bulo    854815
20  San Antonio Bulo Bulo    860832
21  San Antonio Bulo Bulo    921022
22  San Antonio Bulo Bulo    921026
23  San Antonio Bulo Bulo    921760
24  San Antonio Bulo Bulo   1006208
25  San Antonio Bulo Bulo   1016306
26  San Antonio Bulo Bulo   1031642
27                Peñarol   1054256
28                Peñarol   1103605
29  San Antonio Bulo Bulo   1132906
30  San Antonio Bulo Bulo   1211606
31                Peñarol   1256494
32                Peñarol   1350024
33  San Antonio Bulo Bulo   1356957
34                Peñarol   1375764
35                Peñarol   1436129
36                Peñarol   1445403
37                Peñarol   1448091
38  San Antonio Bulo Bulo   1613127
39                Peñarol   1621219
40  San Antonio Bulo Bulo   1639717
41                Peñarol   1646996
42  San Antonio Bulo Bulo   1662516
43  San Antonio Bulo Bulo   1691290
44                Peñarol   1714925
45  San Antonio Bulo Bulo   1733285

Shots

In [24]:
df_shots = pd.DataFrame(json_fotmob['props']['pageProps']['content']['shotmap']['shots'])
df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,period,isOwnGoal,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor
0,2798440475,Miss,8450,1256494,Maximiliano Silvera,95.350877,27.698571,2,NaN,False,...,FirstHalf,False,"{'x': 1.1102230246251565e-16, 'y': 0.119409606...",False,True,NaN,Maximiliano,Silvera,Maximiliano Silvera,#d6a200
1,2798441825,AttemptSaved,8450,834965,Leonardo Fernandez,74.038350,36.440000,7,NaN,False,...,FirstHalf,False,"{'x': 0.6167328042328032, 'y': 0.0424672791005...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200
2,2798441949,AttemptSaved,8450,281238,Maximiliano Olivera,98.631579,42.292812,7,NaN,False,...,FirstHalf,False,"{'x': 0.73776455026455, 'y': 0.215733777830687...",False,True,681451.0,Maximiliano,Olivera,Maximiliano Olivera,#d6a200
3,2798442007,Miss,8450,1436129,Rodrigo Perez,96.701754,31.636250,8,NaN,False,...,FirstHalf,False,"{'x': 1.2735823758471292, 'y': 0.6772486772486...",False,True,NaN,Rodrigo,Perez,Rodrigo Perez,#d6a200
4,2798446287,AttemptSaved,8450,834965,Leonardo Fernandez,72.349029,38.536429,27,NaN,False,...,FirstHalf,False,"{'x': 1.26223544973545, 'y': 0.290476189047619...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200

In [15]:
# Add match round to shots DF
df_shots['matchRound'] = matchRound
df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,isOwnGoal,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,matchRound
0,2798414113,Miss,49681,1363138,Joshuan Berrios,91.000000,25.418125,5,NaN,False,...,False,"{'x': -2.220446049250313e-16, 'y': 0.020534900...",False,True,NaN,Joshuan,Berrios,Joshuan Berrios,#551515,2
1,2798415517,Miss,49681,593211,Gustavo Gonzalez,70.209223,23.718981,10,NaN,False,...,False,"{'x': 0, 'y': 0.030009718309976712, 'zoomRatio...",False,False,NaN,Gustavo,Gonzalez,Gustavo Gonzalez,#551515,2
2,2798416179,AttemptSaved,8517,501636,Jefferson Savarino,78.205340,28.286905,12,NaN,False,...,False,"{'x': 0.9394841269841275, 'y': 0.4195767175132...",False,False,800702.0,Jefferson,Savarino,Jefferson Savarino,#181818,2
3,2798416199,Miss,8517,1028704,Santiago Rodriguez,95.640351,38.788571,12,NaN,False,...,False,"{'x': 1.0685432013562148, 'y': 0.6772486772486...",False,True,NaN,Santiago,Rodriguez,Santiago Rodriguez,#181818,2
4,2798416929,Miss,8517,281240,Gonzalo Mastriani,90.400000,33.618750,15,NaN,False,...,False,"{'x': 1.8956720721422258, 'y': 0.6772486772486...",False,True,NaN,Gonzalo,Mastriani,Gonzalo Mastriani,#181818,2

In [25]:
new_df['player_id'] = new_df['player_id'].astype(int)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   teamName   46 non-null     object
 1   player_id  46 non-null     int64
dtypes: int64(1), object(1)
memory usage: 868.0+ bytes

In [ ]:
# Compare the two dataframes
df_shots['teamName'] = df_shots['playerId'].map(new_df.set_index('player_id')['teamName'])
df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,isOwnGoal,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName
0,2798440475,Miss,8450,1256494,Maximiliano Silvera,95.350877,27.698571,2,NaN,False,...,False,"{'x': 1.1102230246251565e-16, 'y': 0.119409606...",False,True,NaN,Maximiliano,Silvera,Maximiliano Silvera,#d6a200,Peñarol
1,2798441825,AttemptSaved,8450,834965,Leonardo Fernandez,74.038350,36.440000,7,NaN,False,...,False,"{'x': 0.6167328042328032, 'y': 0.0424672791005...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol
2,2798441949,AttemptSaved,8450,281238,Maximiliano Olivera,98.631579,42.292812,7,NaN,False,...,False,"{'x': 0.73776455026455, 'y': 0.215733777830687...",False,True,681451.0,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol
3,2798442007,Miss,8450,1436129,Rodrigo Perez,96.701754,31.636250,8,NaN,False,...,False,"{'x': 1.2735823758471292, 'y': 0.6772486772486...",False,True,NaN,Rodrigo,Perez,Rodrigo Perez,#d6a200,Peñarol
4,2798446287,AttemptSaved,8450,834965,Leonardo Fernandez,72.349029,38.536429,27,NaN,False,...,False,"{'x': 1.26223544973545, 'y': 0.290476189047619...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol
5,2798450493,AttemptSaved,1297060,211145,Carlos Suarez,93.900000,25.707187,41,NaN,True,...,False,"{'x': 0.1729497354497358, 'y': 0.1172096903174...",False,True,NaN,Carlos,Suarez,Carlos Suarez,#00b1e6,San Antonio Bulo Bulo
6,2798451165,AttemptSaved,8450,834965,Leonardo Fernandez,77.980097,13.380853,43,NaN,False,...,False,"{'x': 0.8789682539682532, 'y': 0.2904761890476...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol
7,2798451179,Miss,8450,281238,Maximiliano Olivera,90.800000,36.058750,44,NaN,False,...,False,"{'x': 1.3654321458186596, 'y': 0.6772486772486...",False,True,NaN,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol
8,2798452507,Miss,1297060,1031642,Mario Otazu,89.800000,21.547006,45,2.0,False,...,False,"{'x': 0, 'y': 0.3031045370954118, 'zoomRatio':...",False,True,NaN,Mario,Otazu,Mario Otazu,#00b1e6,San Antonio Bulo Bulo
9,2798456991,AttemptSaved,8450,281238,Maximiliano Olivera,79.331553,47.854268,46,NaN,True,...,False,"{'x': 0.9193121693121694, 'y': 0.3227513211640...",False,False,NaN,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol
10,2798458169,Miss,8450,391991,Jaime Báez,74.038350,45.612229,50,NaN,False,...,False,"{'x': 0, 'y': 0.030058726001073427, 'zoomRatio...",False,False,NaN,Jaime,Báez,Jaime Báez,#d6a200,Peñarol
11,2798458661,Miss,8450,834965,Leonardo Fernandez,74.038350,5.968910,51,NaN,False,...,False,"{'x': 0.8380108948794273, 'y': 0.6772486772486...",False,False,NaN,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol
12,2798459377,Miss,8450,834965,Leonardo Fernandez,90.000000,11.609858,53,NaN,False,...,False,"{'x': 0, 'y': 0.5806392630749795, 'zoomRatio':...",False,False,NaN,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol
13,2798459929,AttemptSaved,8450,363486,Hector Villalba,96.894737,41.367812,55,NaN,False,...,False,"{'x': 0.2738095238095226, 'y': 0.0543581172486...",False,True,681451.0,Hector,Villalba,Hector Villalba,#d6a200,Peñarol
14,2798460963,AttemptSaved,8450,834965,Leonardo Fernandez,80.683010,21.547006,57,NaN,False,...,False,"{'x': 1.0403439153439162, 'y': 0.0645502642328...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol
15,2798462033,Goal,8450,363486,Hector Villalba,91.400000,31.941250,60,NaN,False,...,False,"{'x': 1.8472222222222223, 'y': 0.1613756605820...",False,True,681451.0,Hector,Villalba,Hector Villalba,#d6a200,Peñarol
16,2798462549,AttemptSaved,8450,1350024,Pedro Milans,94.096491,22.387771,63,NaN,False,...,False,"{'x': 1.282407407407408, 'y': 0.46204399661375...",False,True,681451.0,Pedro,Milans,Pedro Milans,#d6a200,Peñarol
17,2798464303,AttemptSaved,8450,1375764,Ignacio Sosa,77.980097,47.013503,72,NaN,True,...,False,"{'x': 1.0201719576719581, 'y': 0.3227513211640...",False,False,NaN,Ignacio,Sosa,Ignacio Sosa,#d6a200,Peñarol
18,2798464323,AttemptSaved,8450,1375764,Ignacio Sosa,76.403398,36.363750,72,NaN,False,...,False,"{'x': 1.3832671957671967, 'y': 0.3006683360317...",False,False,681451.0,Ignacio,Sosa,Ignacio Sosa,#d6a200,Peñarol
19,2798465515,AttemptSaved,8450,1054256,Alexander Machado,85.923529,37.660000,78,NaN,True,...,False,"{'x': 0.29398148148148073, 'y': 0.322751321164...",False,False,NaN,Alexander,Machado,Alexander Machado,#d6a200,Peñarol
20,2798466685,Miss,1297060,316023,Jorge Flores,83.498544,44.561274,82,NaN,False,...,False,"{'x': 0.016201397337563317, 'y': 0.67724867724...",False,False,NaN,Jorge,Flores,Jorge Flores,#00b1e6,San Antonio Bulo Bulo
21,2798467051,Miss,1297060,1356957,Jose Martinez,98.245614,45.822420,83,NaN,False,...,False,"{'x': 0.49504117880176535, 'y': 0.677248677248...",False,True,NaN,Jose,Martinez,Jose Martinez,#00b1e6,San Antonio Bulo Bulo
22,2798468095,AttemptSaved,1297060,1356957,Jose Martinez,93.600000,32.703750,87,NaN,True,...,False,"{'x': 0.455357142857142, 'y': 0.32275132116402...",False,True,NaN,Jose,Martinez,Jose Martinez,#00b1e6,San Antonio Bulo Bulo
23,2798468113,Miss,1297060,921026,Julio Herrera,80.007282,31.255000,87,NaN,False,...,False,"{'x': 0, 'y': 0.025473662778555336, 'zoomRatio...",False,False,NaN,Julio,Herrera,Julio Herrera,#00b1e6,San Antonio Bulo Bulo
24,2798469359,AttemptSaved,1297060,1356957,Jose Martinez,77.642233,31.178750,90,2.0,True,...,False,"{'x': 1.1815476190476193, 'y': 0.3227513211640...",False,False,NaN,Jose,Martinez,Jose Martinez,#00b1e6,San Antonio Bulo Bulo
25,2798470129,Goal,8450,1054256,Alexander Machado,88.285294,41.225952,90,4.0,False,...,False,"{'x': 1.8472222222222223, 'y': 0.1392926754497...",False,False,681451.0,Alexander,Machado,Alexander Machado,#d6a200,Peñarol

In [ ]:
# Same result as above, but using merge
df_shots = pd.merge(
    df_shots,
    new_df[['player_id', 'teamName']],
    left_on='playerId',
    right_on='player_id',
    how='left'  # keeps all rows from df_shots even if no match
).drop('player_id', axis=1)  # drop the redundant column

df_shots

In [32]:
h_team

'Club Atletico Penarol'

Options to get home or away team

In [ ]:
# Get home and away team -> worked fine until I hit Club Atletico Penarol vs Peñarol | Check DeepSick
# df_shots['h_a'] = df_shots['teamName'].apply(lambda x: 'h' if x == h_team else 'a') # does not work with Botafogo RJ & Botafogo

from fuzzywuzzy import fuzz

# Define a similarity threshold (e.g., 70 means 70% similar)
threshold = 70

df_shots['h_a'] = df_shots['teamName'].apply(
    lambda x: 'h' if fuzz.ratio(x.lower(), h_team.lower()) >= threshold else 'a'
)

df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName,h_a
0,2798440475,Miss,8450,1256494,Maximiliano Silvera,95.350877,27.698571,2,NaN,False,...,"{'x': 1.1102230246251565e-16, 'y': 0.119409606...",False,True,NaN,Maximiliano,Silvera,Maximiliano Silvera,#d6a200,Peñarol,a
1,2798441825,AttemptSaved,8450,834965,Leonardo Fernandez,74.038350,36.440000,7,NaN,False,...,"{'x': 0.6167328042328032, 'y': 0.0424672791005...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,a
2,2798441949,AttemptSaved,8450,281238,Maximiliano Olivera,98.631579,42.292812,7,NaN,False,...,"{'x': 0.73776455026455, 'y': 0.215733777830687...",False,True,681451.0,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol,a
3,2798442007,Miss,8450,1436129,Rodrigo Perez,96.701754,31.636250,8,NaN,False,...,"{'x': 1.2735823758471292, 'y': 0.6772486772486...",False,True,NaN,Rodrigo,Perez,Rodrigo Perez,#d6a200,Peñarol,a
4,2798446287,AttemptSaved,8450,834965,Leonardo Fernandez,72.349029,38.536429,27,NaN,False,...,"{'x': 1.26223544973545, 'y': 0.290476189047619...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,a

In [ ]:
# Option for Peñarol
from fuzzywuzzy import fuzz

threshold = 80  # Adjust based on testing

df_shots['h_a'] = df_shots['teamName'].apply(
    lambda x: 'h' if fuzz.partial_ratio(x.lower(), h_team.lower()) >= threshold else 'a'
)

df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName,h_a
0,2798440475,Miss,8450,1256494,Maximiliano Silvera,95.350877,27.698571,2,NaN,False,...,"{'x': 1.1102230246251565e-16, 'y': 0.119409606...",False,True,NaN,Maximiliano,Silvera,Maximiliano Silvera,#d6a200,Peñarol,h
1,2798441825,AttemptSaved,8450,834965,Leonardo Fernandez,74.038350,36.440000,7,NaN,False,...,"{'x': 0.6167328042328032, 'y': 0.0424672791005...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,h
2,2798441949,AttemptSaved,8450,281238,Maximiliano Olivera,98.631579,42.292812,7,NaN,False,...,"{'x': 0.73776455026455, 'y': 0.215733777830687...",False,True,681451.0,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol,h
3,2798442007,Miss,8450,1436129,Rodrigo Perez,96.701754,31.636250,8,NaN,False,...,"{'x': 1.2735823758471292, 'y': 0.6772486772486...",False,True,NaN,Rodrigo,Perez,Rodrigo Perez,#d6a200,Peñarol,h
4,2798446287,AttemptSaved,8450,834965,Leonardo Fernandez,72.349029,38.536429,27,NaN,False,...,"{'x': 1.26223544973545, 'y': 0.290476189047619...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,h
5,2798450493,AttemptSaved,1297060,211145,Carlos Suarez,93.900000,25.707187,41,NaN,True,...,"{'x': 0.1729497354497358, 'y': 0.1172096903174...",False,True,NaN,Carlos,Suarez,Carlos Suarez,#00b1e6,San Antonio Bulo Bulo,a
6,2798451165,AttemptSaved,8450,834965,Leonardo Fernandez,77.980097,13.380853,43,NaN,False,...,"{'x': 0.8789682539682532, 'y': 0.2904761890476...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,h
7,2798451179,Miss,8450,281238,Maximiliano Olivera,90.800000,36.058750,44,NaN,False,...,"{'x': 1.3654321458186596, 'y': 0.6772486772486...",False,True,NaN,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol,h
8,2798452507,Miss,1297060,1031642,Mario Otazu,89.800000,21.547006,45,2.0,False,...,"{'x': 0, 'y': 0.3031045370954118, 'zoomRatio':...",False,True,NaN,Mario,Otazu,Mario Otazu,#00b1e6,San Antonio Bulo Bulo,a
9,2798456991,AttemptSaved,8450,281238,Maximiliano Olivera,79.331553,47.854268,46,NaN,True,...,"{'x': 0.9193121693121694, 'y': 0.3227513211640...",False,False,NaN,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol,h
10,2798458169,Miss,8450,391991,Jaime Báez,74.038350,45.612229,50,NaN,False,...,"{'x': 0, 'y': 0.030058726001073427, 'zoomRatio...",False,False,NaN,Jaime,Báez,Jaime Báez,#d6a200,Peñarol,h
11,2798458661,Miss,8450,834965,Leonardo Fernandez,74.038350,5.968910,51,NaN,False,...,"{'x': 0.8380108948794273, 'y': 0.6772486772486...",False,False,NaN,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,h
12,2798459377,Miss,8450,834965,Leonardo Fernandez,90.000000,11.609858,53,NaN,False,...,"{'x': 0, 'y': 0.5806392630749795, 'zoomRatio':...",False,False,NaN,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,h
13,2798459929,AttemptSaved,8450,363486,Hector Villalba,96.894737,41.367812,55,NaN,False,...,"{'x': 0.2738095238095226, 'y': 0.0543581172486...",False,True,681451.0,Hector,Villalba,Hector Villalba,#d6a200,Peñarol,h
14,2798460963,AttemptSaved,8450,834965,Leonardo Fernandez,80.683010,21.547006,57,NaN,False,...,"{'x': 1.0403439153439162, 'y': 0.0645502642328...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,h
15,2798462033,Goal,8450,363486,Hector Villalba,91.400000,31.941250,60,NaN,False,...,"{'x': 1.8472222222222223, 'y': 0.1613756605820...",False,True,681451.0,Hector,Villalba,Hector Villalba,#d6a200,Peñarol,h
16,2798462549,AttemptSaved,8450,1350024,Pedro Milans,94.096491,22.387771,63,NaN,False,...,"{'x': 1.282407407407408, 'y': 0.46204399661375...",False,True,681451.0,Pedro,Milans,Pedro Milans,#d6a200,Peñarol,h
17,2798464303,AttemptSaved,8450,1375764,Ignacio Sosa,77.980097,47.013503,72,NaN,True,...,"{'x': 1.0201719576719581, 'y': 0.3227513211640...",False,False,NaN,Ignacio,Sosa,Ignacio Sosa,#d6a200,Peñarol,h
18,2798464323,AttemptSaved,8450,1375764,Ignacio Sosa,76.403398,36.363750,72,NaN,False,...,"{'x': 1.3832671957671967, 'y': 0.3006683360317...",False,False,681451.0,Ignacio,Sosa,Ignacio Sosa,#d6a200,Peñarol,h
19,2798465515,AttemptSaved,8450,1054256,Alexander Machado,85.923529,37.660000,78,NaN,True,...,"{'x': 0.29398148148148073, 'y': 0.322751321164...",False,False,NaN,Alexander,Machado,Alexander Machado,#d6a200,Peñarol,h
20,2798466685,Miss,1297060,316023,Jorge Flores,83.498544,44.561274,82,NaN,False,...,"{'x': 0.016201397337563317, 'y': 0.67724867724...",False,False,NaN,Jorge,Flores,Jorge Flores,#00b1e6,San Antonio Bulo Bulo,a
21,2798467051,Miss,1297060,1356957,Jose Martinez,98.245614,45.822420,83,NaN,False,...,"{'x': 0.49504117880176535, 'y': 0.677248677248...",False,True,NaN,Jose,Martinez,Jose Martinez,#00b1e6,San Antonio Bulo Bulo,a
22,2798468095,AttemptSaved,1297060,1356957,Jose Martinez,93.600000,32.703750,87,NaN,True,...,"{'x': 0.455357142857142, 'y': 0.32275132116402...",False,True,NaN,Jose,Martinez,Jose Martinez,#00b1e6,San Antonio Bulo Bulo,a
23,2798468113,Miss,1297060,921026,Julio Herrera,80.007282,31.255000,87,NaN,False,...,"{'x': 0, 'y': 0.025473662778555336, 'zoomRatio...",False,False,NaN,Julio,Herrera,Julio Herrera,#00b1e6,San Antonio Bulo Bulo,a
24,2798469359,AttemptSaved,1297060,1356957,Jose Martinez,77.642233,31.178750,90,2.0,True,...,"{'x': 1.1815476190476193, 'y': 0.3227513211640...",False,False,NaN,Jose,Martinez,Jose Martinez,#00b1e6,San Antonio Bulo Bulo,a
25,2798470129,Goal,8450,1054256,Alexander Machado,88.285294,41.225952,90,4.0,False,...,"{'x': 1.8472222222222223, 'y': 0.1392926754497...",False,False,681451.0,Alexander,Machado,Alexander Machado,#d6a200,Peñarol,h

In [54]:
# DF to CSV
df_shots.to_csv('/home/axel/Code/Python/axel/streamlit/csv/CerroBolivar.csv', index=False)

Check concat file

In [2]:
shots = pd.read_csv('/home/axel/Code/Python/axel/streamlit/concat_files/concat_shots.csv')

Most shots

In [78]:
shots['teamName'].value_counts().sort_values(ascending=False)

# teams_df = shots['teamName'].value_counts().reset_index()
# teams_df.columns = ['teamName', 'count']
# teams_df.sort_values(by='count', ascending=False)

teamName
Racing Club                              24
Atlético Nacional                        22
Bahia                                    21
Palmeiras                                19
Vélez Sarsfield                          19
Cerro Porteño                            19
Talleres de Córdoba                      17
Central Córdoba (Santiago del Estero)    17
Barcelona de Guayaquil                   17
Alianza Lima                             16
Olimpia                                  15
Fortaleza EC                             14
Sporting Cristal                         14
Estudiantes de La Plata                  14
San Antonio Bulo Bulo                    14
Flamengo                                 12
Atlético Bucaramanga                     12
Nacional                                 11
Libertad                                 11
Bolívar                                  10
River Plate                              10
Independiente del Valle                  10
Colo-Colo                                 9
Internacional                             8
Botafogo                                  7
Universitario de Deportes                 6
Carabobo FC                               6
Deportivo Táchira                         6
Universidad de Chile                      6
São Paulo                                 5
LDU Quito                                 5
Peñarol                                   4
Name: count, dtype: int64

Filter by shots on target

In [39]:
target_shots = shots[shots['isOnTarget'] == True]
target_shots.shape

(238, 31)

In [54]:
target_shots.groupby('teamName')['isOnTarget'].count().reset_index(name='count').sort_values(by='count', ascending=False).reset_index(drop=True)

                                 teamName  count
0                             Racing Club     16
1                       Atlético Nacional     14
2                         Vélez Sarsfield     12
3                  Barcelona de Guayaquil     12
4                                   Bahia     11
5                               Palmeiras     11
6   Central Córdoba (Santiago del Estero)     10
7                            Alianza Lima     10
8                        Sporting Cristal     10
9                     Talleres de Córdoba     10
10                  San Antonio Bulo Bulo      9
11                                Olimpia      9
12                           Fortaleza EC      9
13                               Nacional      8
14                          Cerro Porteño      8
15                   Atlético Bucaramanga      7
16                          Internacional      7
17                Estudiantes de La Plata      7
18                               Flamengo      6
19                               Libertad      6
20                               Botafogo      6
21                                Bolívar      6
22                              Colo-Colo      6
23                            River Plate      5
24              Universitario de Deportes      4
25                              São Paulo      4
26                            Carabobo FC      4
27                Independiente del Valle      3
28                   Universidad de Chile      3
29                      Deportivo Táchira      2
30                              LDU Quito      2
31                                Peñarol      1

In [3]:
shots.columns

Index(['id', 'eventType', 'teamId', 'playerId', 'playerName', 'x', 'y', 'min',
       'minAdded', 'isBlocked', 'isOnTarget', 'blockedX', 'blockedY',
       'goalCrossedY', 'goalCrossedZ', 'expectedGoals',
       'expectedGoalsOnTarget', 'shotType', 'situation', 'period', 'isOwnGoal',
       'onGoalShot', 'isSavedOffLine', 'isFromInsideBox', 'keeperId',
       'firstName', 'lastName', 'fullName', 'teamColor', 'teamName',
       'source_file'],
      dtype='object')