In [1]:
import requests
import json
from bs4 import BeautifulSoup as bs
import pandas as pd

In [48]:
url = input("Enter the URL of the page to scrape: ")
r = requests.get(url)
soup = bs(r.content)
json_fotmob = json.loads(soup.find('script', attrs={'id': '__NEXT_DATA__'}).contents[0])

In [49]:
# General match info
json_fotmob['props']['pageProps']['general']

{'matchId': '4756697',
 'matchName': 'Botafogo RJ-vs-Carabobo FC_Tue, Apr 8, 2025, 22:00 UTC',
 'matchRound': '2',
 'teamColors': {'darkMode': {'home': '#ffffff', 'away': '#943521'},
  'lightMode': {'home': '#181818', 'away': '#551515'},
  'fontDarkMode': {'home': 'rgba(29, 29, 29, 1.0)',
   'away': 'rgba(255, 255, 255, 1.0)'},
  'fontLightMode': {'home': 'rgba(255, 255, 255, 1.0)',
   'away': 'rgba(255, 255, 255, 1.0)'}},
 'leagueId': 898417,
 'leagueName': 'Copa Libertadores Grp. A',
 'leagueRoundName': '2',
 'parentLeagueId': 45,
 'countryCode': 'INT-2',
 'parentLeagueName': 'Copa Libertadores',
 'parentLeagueSeason': '2025',
 'parentLeagueTopScorerLink': 'https://data.fotmob.com/stats/45/season/25464/goals.json',
 'parentLeagueTournamentId': 25464,
 'homeTeam': {'name': 'Botafogo RJ', 'id': 8517},
 'awayTeam': {'name': 'Carabobo FC', 'id': 49681},
 'coverageLevel': 'xG',
 'matchTimeUTC': 'Tue, Apr 8, 2025, 22:00 UTC',
 'matchTimeUTCDate': '2025-04-08T22:00:00.000Z',
 'started': True,
 'finished': True}

In [4]:
matchRound = int(json_fotmob['props']['pageProps']['general']['matchRound'])
matchRound

1

In [12]:
type(matchRound)

int

In [50]:
h_team = json_fotmob['props']['pageProps']['general']['homeTeam']['name']
h_team

'Botafogo RJ'

In [51]:
a_team = json_fotmob['props']['pageProps']['general']['awayTeam']['name']
a_team

'Carabobo FC'

In [52]:
df = pd.DataFrame(json_fotmob['props']['pageProps']['content']['playerStats'])
df

,188652,281240,423496,428672,501636,593211,634868,641140,657969,749834,...,1436176,1453231,1476545,1578668,1611001,1615062,1626265,1732667,1732679,1739032
name,Allan,Gonzalo Mastriani,Marcel Guaramato,Alex Telles,Jefferson Savarino,Gustavo Gonzalez,Marlon Freitas,Robert Hernandez,Alexander Barboza,John Victor,...,Mateo Ponte,Ezequiel Neira,Cuiabano,Newton,Freiver Ruiz,Franner Lopez,Kaue,Kauan Lindes,Sebastian Mendoza,Fernando Garcia
id,188652,281240,423496,428672,501636,593211,634868,641140,657969,749834,...,1436176,1453231,1476545,1578668,1611001,1615062,1626265,1732667,1732679,1739032
optaId,119765,153330,166518,152590,196666,196304,219357,149237,213531,221389,...,609049,502487,560441,608580,485122,612930,608581,646823,654211,693358
teamId,8517,8517,49681,8517,8517,49681,8517,49681,8517,8517,...,8517,49681,8517,8517,49681,49681,8517,8517,49681,49681
teamName,Botafogo,Botafogo,Carabobo FC,Botafogo,Botafogo,Carabobo FC,Botafogo,Carabobo FC,Botafogo,Botafogo,...,Botafogo,Carabobo FC,Botafogo,Botafogo,Carabobo FC,Carabobo FC,Botafogo,Botafogo,Carabobo FC,Carabobo FC
isGoalkeeper,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
stats,[],"[{'title': 'Top stats', 'key': 'top_stats', 's...",[],"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...",...,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'title': 'Top stats', 'key': 'top_stats', 's...",[],[],"[{'title': 'Top stats', 'key': 'top_stats', 's...",[],[],[],[]
shotmap,[],"[{'id': 2798416929, 'eventType': 'Miss', 'team...",[],[],"[{'id': 2798416179, 'eventType': 'AttemptSaved...","[{'id': 2798415517, 'eventType': 'Miss', 'team...",[],[],"[{'id': 2798422359, 'eventType': 'Miss', 'team...",[],...,[],[],"[{'id': 2798437109, 'eventType': 'Miss', 'team...",[],[],[],[],[],[],[]
funFacts,[],[],[],[],"[{'key': 'fun_fact_low_touches', 'fallback': '...",[],[],[],"[{'key': 'fun_fact_motm', 'fallback': 'Alexand...",[],...,[],[],[],[],[],[],[],[],[],[]

In [53]:
df = df.T
df.head()

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shotmap,funFacts
188652,Allan,188652,119765,8517,Botafogo,False,[],[],[]
281240,Gonzalo Mastriani,281240,153330,8517,Botafogo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798416929, 'eventType': 'Miss', 'team...",[]
423496,Marcel Guaramato,423496,166518,49681,Carabobo FC,False,[],[],[]
428672,Alex Telles,428672,152590,8517,Botafogo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",[],[]
501636,Jefferson Savarino,501636,196666,8517,Botafogo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798416179, 'eventType': 'AttemptSaved...","[{'key': 'fun_fact_low_touches', 'fallback': '..."

In [54]:
df['player_id'] = df.index
df.reset_index(drop=True, inplace=True)
df.head()

,name,id,optaId,teamId,teamName,isGoalkeeper,stats,shotmap,funFacts,player_id
0,Allan,188652,119765,8517,Botafogo,False,[],[],[],188652
1,Gonzalo Mastriani,281240,153330,8517,Botafogo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798416929, 'eventType': 'Miss', 'team...",[],281240
2,Marcel Guaramato,423496,166518,49681,Carabobo FC,False,[],[],[],423496
3,Alex Telles,428672,152590,8517,Botafogo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...",[],[],428672
4,Jefferson Savarino,501636,196666,8517,Botafogo,False,"[{'title': 'Top stats', 'key': 'top_stats', 's...","[{'id': 2798416179, 'eventType': 'AttemptSaved...","[{'key': 'fun_fact_low_touches', 'fallback': '...",501636

In [55]:
new_df = df[['teamName', 'player_id']].copy()
new_df

       teamName player_id
0      Botafogo    188652
1      Botafogo    281240
2   Carabobo FC    423496
3      Botafogo    428672
4      Botafogo    501636
5   Carabobo FC    593211
6      Botafogo    634868
7   Carabobo FC    641140
8      Botafogo    657969
9      Botafogo    749834
10     Botafogo    754504
11  Carabobo FC    800702
12  Carabobo FC    889539
13     Botafogo    905498
14     Botafogo    921070
15  Carabobo FC    926070
16  Carabobo FC   1023077
17     Botafogo   1028704
18  Carabobo FC   1031644
19  Carabobo FC   1124611
20     Botafogo   1137664
21     Botafogo   1210064
22  Carabobo FC   1211302
23     Botafogo   1248672
24  Carabobo FC   1257669
25     Botafogo   1262084
26  Carabobo FC   1299971
27  Carabobo FC   1330400
28     Botafogo   1350129
29  Carabobo FC   1353300
30  Carabobo FC   1354125
31  Carabobo FC   1356175
32  Carabobo FC   1363138
33  Carabobo FC   1371883
34     Botafogo   1373118
35     Botafogo   1391209
36     Botafogo   1436176
37  Carabobo FC   1453231
38     Botafogo   1476545
39     Botafogo   1578668
40  Carabobo FC   1611001
41  Carabobo FC   1615062
42     Botafogo   1626265
43     Botafogo   1732667
44  Carabobo FC   1732679
45  Carabobo FC   1739032

Shots

In [56]:
df_shots = pd.DataFrame(json_fotmob['props']['pageProps']['content']['shotmap']['shots'])
df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,period,isOwnGoal,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor
0,2798414113,Miss,49681,1363138,Joshuan Berrios,91.000000,25.418125,5,NaN,False,...,FirstHalf,False,"{'x': -2.220446049250313e-16, 'y': 0.020534900...",False,True,NaN,Joshuan,Berrios,Joshuan Berrios,#551515
1,2798415517,Miss,49681,593211,Gustavo Gonzalez,70.209223,23.718981,10,NaN,False,...,FirstHalf,False,"{'x': 0, 'y': 0.030009718309976712, 'zoomRatio...",False,False,NaN,Gustavo,Gonzalez,Gustavo Gonzalez,#551515
2,2798416179,AttemptSaved,8517,501636,Jefferson Savarino,76.516019,29.547619,12,NaN,False,...,FirstHalf,False,"{'x': 0.9394841269841275, 'y': 0.4195767175132...",False,False,800702.0,Jefferson,Savarino,Jefferson Savarino,#181818
3,2798416199,Miss,8517,1028704,Santiago Rodriguez,95.640351,38.788571,12,NaN,False,...,FirstHalf,False,"{'x': 1.0685432013562148, 'y': 0.6772486772486...",False,True,NaN,Santiago,Rodriguez,Santiago Rodriguez,#181818
4,2798416929,Miss,8517,281240,Gonzalo Mastriani,90.400000,33.618750,15,NaN,False,...,FirstHalf,False,"{'x': 1.8956720721422258, 'y': 0.6772486772486...",False,True,NaN,Gonzalo,Mastriani,Gonzalo Mastriani,#181818

In [15]:
# Add match round to shots DF
df_shots['matchRound'] = matchRound
df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,isOwnGoal,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,matchRound
0,2798414113,Miss,49681,1363138,Joshuan Berrios,91.000000,25.418125,5,NaN,False,...,False,"{'x': -2.220446049250313e-16, 'y': 0.020534900...",False,True,NaN,Joshuan,Berrios,Joshuan Berrios,#551515,2
1,2798415517,Miss,49681,593211,Gustavo Gonzalez,70.209223,23.718981,10,NaN,False,...,False,"{'x': 0, 'y': 0.030009718309976712, 'zoomRatio...",False,False,NaN,Gustavo,Gonzalez,Gustavo Gonzalez,#551515,2
2,2798416179,AttemptSaved,8517,501636,Jefferson Savarino,78.205340,28.286905,12,NaN,False,...,False,"{'x': 0.9394841269841275, 'y': 0.4195767175132...",False,False,800702.0,Jefferson,Savarino,Jefferson Savarino,#181818,2
3,2798416199,Miss,8517,1028704,Santiago Rodriguez,95.640351,38.788571,12,NaN,False,...,False,"{'x': 1.0685432013562148, 'y': 0.6772486772486...",False,True,NaN,Santiago,Rodriguez,Santiago Rodriguez,#181818,2
4,2798416929,Miss,8517,281240,Gonzalo Mastriani,90.400000,33.618750,15,NaN,False,...,False,"{'x': 1.8956720721422258, 'y': 0.6772486772486...",False,True,NaN,Gonzalo,Mastriani,Gonzalo Mastriani,#181818,2

In [57]:
new_df['player_id'] = new_df['player_id'].astype(int)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   teamName   46 non-null     object
 1   player_id  46 non-null     int64
dtypes: int64(1), object(1)
memory usage: 868.0+ bytes

In [58]:
# Compare the two dataframes
df_shots['teamName'] = df_shots['playerId'].map(new_df.set_index('player_id')['teamName'])
df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,isOwnGoal,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName
0,2798414113,Miss,49681,1363138,Joshuan Berrios,91.000000,25.418125,5,NaN,False,...,False,"{'x': -2.220446049250313e-16, 'y': 0.020534900...",False,True,NaN,Joshuan,Berrios,Joshuan Berrios,#551515,Carabobo FC
1,2798415517,Miss,49681,593211,Gustavo Gonzalez,70.209223,23.718981,10,NaN,False,...,False,"{'x': 0, 'y': 0.030009718309976712, 'zoomRatio...",False,False,NaN,Gustavo,Gonzalez,Gustavo Gonzalez,#551515,Carabobo FC
2,2798416179,AttemptSaved,8517,501636,Jefferson Savarino,76.516019,29.547619,12,NaN,False,...,False,"{'x': 0.9394841269841275, 'y': 0.4195767175132...",False,False,800702.0,Jefferson,Savarino,Jefferson Savarino,#181818,Botafogo
3,2798416199,Miss,8517,1028704,Santiago Rodriguez,95.640351,38.788571,12,NaN,False,...,False,"{'x': 1.0685432013562148, 'y': 0.6772486772486...",False,True,NaN,Santiago,Rodriguez,Santiago Rodriguez,#181818,Botafogo
4,2798416929,Miss,8517,281240,Gonzalo Mastriani,90.400000,33.618750,15,NaN,False,...,False,"{'x': 1.8956720721422258, 'y': 0.6772486772486...",False,True,NaN,Gonzalo,Mastriani,Gonzalo Mastriani,#181818,Botafogo

In [ ]:
# 2️⃣👍🏼👎🏼 Same result as above, but using merge
df_shots = pd.merge(
    df_shots,
    new_df[['player_id', 'teamName']],
    left_on='playerId',
    right_on='player_id',
    how='left'  # keeps all rows from df_shots even if no match
).drop('player_id', axis=1)  # drop the redundant column

df_shots

Options to get home or away team

In [ ]:
# ❌ Get home and away team -> worked fine until I hit Botafogo RJ & Botafogo | Check DS
df_shots['h_a'] = df_shots['teamName'].apply(lambda x: 'h' if x == h_team else 'a')

In [22]:
from fuzzywuzzy import fuzz

In [ ]:
# ❌ fuzzywuzzy to handle slight variation -> worked fine until I hit Club Atletico Penarol & Peñarol

# Define a similarity threshold (e.g., 70 means 70% similar)
threshold = 70

df_shots['h_a'] = df_shots['teamName'].apply(
    lambda x: 'h' if fuzz.ratio(x.lower(), h_team.lower()) >= threshold else 'a'
)

df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName,h_a
0,2798440475,Miss,8450,1256494,Maximiliano Silvera,95.350877,27.698571,2,NaN,False,...,"{'x': 1.1102230246251565e-16, 'y': 0.119409606...",False,True,NaN,Maximiliano,Silvera,Maximiliano Silvera,#d6a200,Peñarol,a
1,2798441825,AttemptSaved,8450,834965,Leonardo Fernandez,74.038350,36.440000,7,NaN,False,...,"{'x': 0.6167328042328032, 'y': 0.0424672791005...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,a
2,2798441949,AttemptSaved,8450,281238,Maximiliano Olivera,98.631579,42.292812,7,NaN,False,...,"{'x': 0.73776455026455, 'y': 0.215733777830687...",False,True,681451.0,Maximiliano,Olivera,Maximiliano Olivera,#d6a200,Peñarol,a
3,2798442007,Miss,8450,1436129,Rodrigo Perez,96.701754,31.636250,8,NaN,False,...,"{'x': 1.2735823758471292, 'y': 0.6772486772486...",False,True,NaN,Rodrigo,Perez,Rodrigo Perez,#d6a200,Peñarol,a
4,2798446287,AttemptSaved,8450,834965,Leonardo Fernandez,72.349029,38.536429,27,NaN,False,...,"{'x': 1.26223544973545, 'y': 0.290476189047619...",False,False,681451.0,Leonardo,Fernandez,Leonardo Fernandez,#d6a200,Peñarol,a

In [24]:
# ❌ Option for Peñarol -> worked fine until I hit Atletico Nacional vs Nacional | Check DS

threshold = 80  # Adjust based on testing

df_shots['h_a'] = df_shots['teamName'].apply(
    lambda x: 'h' if fuzz.partial_ratio(x.lower(), h_team.lower()) >= threshold else 'a'
)

df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName,h_a
0,2795252373,Miss,6368,925847,Felipe Roman,82.710194,20.706242,1,NaN,False,...,"{'x': 0, 'y': 0.028390145309295595, 'zoomRatio...",False,False,NaN,Felipe,Roman,Felipe Roman,#008449,Atlético Nacional,h
1,2795253047,AttemptSaved,6368,1205222,Marino Hinestroza,88.600000,45.402038,3,NaN,True,...,"{'x': 0.5763888888888888, 'y': 0.3227513211640...",False,True,NaN,Marino,Hinestroza,Marino Hinestroza,#008449,Atlético Nacional,h
2,2795255419,AttemptSaved,6368,1205222,Marino Hinestroza,82.822816,17.553376,9,NaN,True,...,"{'x': 1.141203703703705, 'y': 0.32275132116402...",False,False,NaN,Marino,Hinestroza,Marino Hinestroza,#008449,Atlético Nacional,h
3,2795255629,AttemptSaved,8304,1037554,Diego Herazo,99.017544,23.648917,9,NaN,True,...,"{'x': 0.6772486772486757, 'y': 0.2361180717989...",False,True,NaN,Diego,Herazo,Diego Herazo,#1246A9,Nacional,h
4,2795257849,AttemptSaved,6368,1205222,Marino Hinestroza,93.200000,30.268000,14,NaN,True,...,"{'x': 1.141203703703705, 'y': 0.32275132116402...",False,True,NaN,Marino,Hinestroza,Marino Hinestroza,#008449,Atlético Nacional,h

In [25]:
# ❌ Option for Peñarol -> worked fine until I hit Atletico Nacional vs Nacional | Check DS

df_shots['h_a'] = df_shots['teamName'].apply(
    lambda x: 'h' if fuzz.token_set_ratio(x.lower(), h_team.lower()) >= 75 else 'a'
)

df_shots.head()

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName,h_a
0,2795252373,Miss,6368,925847,Felipe Roman,82.710194,20.706242,1,NaN,False,...,"{'x': 0, 'y': 0.028390145309295595, 'zoomRatio...",False,False,NaN,Felipe,Roman,Felipe Roman,#008449,Atlético Nacional,h
1,2795253047,AttemptSaved,6368,1205222,Marino Hinestroza,88.600000,45.402038,3,NaN,True,...,"{'x': 0.5763888888888888, 'y': 0.3227513211640...",False,True,NaN,Marino,Hinestroza,Marino Hinestroza,#008449,Atlético Nacional,h
2,2795255419,AttemptSaved,6368,1205222,Marino Hinestroza,82.822816,17.553376,9,NaN,True,...,"{'x': 1.141203703703705, 'y': 0.32275132116402...",False,False,NaN,Marino,Hinestroza,Marino Hinestroza,#008449,Atlético Nacional,h
3,2795255629,AttemptSaved,8304,1037554,Diego Herazo,99.017544,23.648917,9,NaN,True,...,"{'x': 0.6772486772486757, 'y': 0.2361180717989...",False,True,NaN,Diego,Herazo,Diego Herazo,#1246A9,Nacional,h
4,2795257849,AttemptSaved,6368,1205222,Marino Hinestroza,93.200000,30.268000,14,NaN,True,...,"{'x': 1.141203703703705, 'y': 0.32275132116402...",False,True,NaN,Marino,Hinestroza,Marino Hinestroza,#008449,Atlético Nacional,h

In [ ]:
# ✅❌Currently last option for Atletico Nacional vs Nacional | Claude

import re
import unicodedata

def normalize_team_name(name):
    """Normalize team name by removing accents and standardizing format"""
    # Convert to lowercase
    name = name.lower()

    # Remove accents
    name = unicodedata.normalize('NFKD', name).encode('ASCII', 'ignore').decode('utf-8')

    # Remove non-alphanumeric characters and standardize spaces
    name = re.sub(r'[^\w\s]', '', name)
    name = re.sub(r'\s+', ' ', name).strip()

    return name

def create_team_mapping(h_team, a_team, known_aliases=None):
    """Create a mapping dictionary for home and away teams with their possible variations"""
    if known_aliases is None:
        known_aliases = {}

    # Normalize the official team names
    norm_h = normalize_team_name(h_team)
    norm_a = normalize_team_name(a_team)

    # Create a mapping with the full names and their normalized versions
    mapping = {
        normalize_team_name(h_team): 'h',
        normalize_team_name(a_team): 'a'
    }

    # Add known aliases from the dictionary
    for team_name, aliases in known_aliases.items():
        if normalize_team_name(team_name) == norm_h:
            for alias in aliases:
                mapping[normalize_team_name(alias)] = 'h'
        elif normalize_team_name(team_name) == norm_a:
            for alias in aliases:
                mapping[normalize_team_name(alias)] = 'a'

    return mapping

def match_team_exact(team_name, mapping):
    """Match team_name to either h_team or a_team based on exact match after normalization"""
    norm_team = normalize_team_name(team_name)

    # Try exact match
    if norm_team in mapping:
        return mapping[norm_team]

    # If no match, return None (to be handled separately)
    return None

# Set up any known team aliases (add more as needed)
team_aliases = {
    "Botafogo RJ": ["Botafogo", "Botafogo de Futebol e Regatas"],
    "Club Atletico Penarol": ["Penarol", "Peñarol", "CA Penarol"],
    "Atletico Nacional": ["Atlético Nacional", "Atletico Nacional Medellin"],
    "Nacional": ["Club Nacional", "Nacional de Montevideo"]
    # Add more teams and their aliases as needed
}

# Create the mapping dictionary
team_mapping = create_team_mapping(h_team, a_team, team_aliases)

# Apply the exact matching function
df_shots['h_a'] = df_shots['teamName'].apply(
    lambda x: match_team_exact(x, team_mapping) or 'unknown'
)

# Handle any 'unknown' matches (could prompt for manual resolution)
if 'unknown' in df_shots['h_a'].values:
    print(f"Unmatched team names: {df_shots.loc[df_shots['h_a'] == 'unknown', 'teamName'].unique()}")
    # Could add code here to handle unknowns

df_shots.head(10)

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,onGoalShot,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,teamName,h_a
0,2798414113,Miss,49681,1363138,Joshuan Berrios,91.000000,25.418125,5,NaN,False,...,"{'x': -2.220446049250313e-16, 'y': 0.020534900...",False,True,NaN,Joshuan,Berrios,Joshuan Berrios,#551515,Carabobo FC,a
1,2798415517,Miss,49681,593211,Gustavo Gonzalez,70.209223,23.718981,10,NaN,False,...,"{'x': 0, 'y': 0.030009718309976712, 'zoomRatio...",False,False,NaN,Gustavo,Gonzalez,Gustavo Gonzalez,#551515,Carabobo FC,a
2,2798416179,AttemptSaved,8517,501636,Jefferson Savarino,76.516019,29.547619,12,NaN,False,...,"{'x': 0.9394841269841275, 'y': 0.4195767175132...",False,False,800702.0,Jefferson,Savarino,Jefferson Savarino,#181818,Botafogo,h
3,2798416199,Miss,8517,1028704,Santiago Rodriguez,95.640351,38.788571,12,NaN,False,...,"{'x': 1.0685432013562148, 'y': 0.6772486772486...",False,True,NaN,Santiago,Rodriguez,Santiago Rodriguez,#181818,Botafogo,h
4,2798416929,Miss,8517,281240,Gonzalo Mastriani,90.400000,33.618750,15,NaN,False,...,"{'x': 1.8956720721422258, 'y': 0.6772486772486...",False,True,NaN,Gonzalo,Mastriani,Gonzalo Mastriani,#181818,Botafogo,h
5,2798418233,AttemptSaved,49681,593211,Gustavo Gonzalez,83.273301,29.547619,20,NaN,True,...,"{'x': 0.5763888888888888, 'y': 0.3227513211640...",False,False,NaN,Gustavo,Gonzalez,Gustavo Gonzalez,#551515,Carabobo FC,a
6,2798418277,AttemptSaved,49681,1023077,Carlos Ramos,80.345146,20.986497,20,NaN,True,...,"{'x': 0.455357142857142, 'y': 0.32275132116402...",False,False,NaN,Carlos,Ramos,Carlos Ramos,#551515,Carabobo FC,a
7,2798418441,AttemptSaved,49681,593211,Gustavo Gonzalez,80.457767,34.228750,21,NaN,False,...,"{'x': 0.41501322751322767, 'y': 0.439961011481...",False,False,749834.0,Gustavo,Gonzalez,Gustavo Gonzalez,#551515,Carabobo FC,a
8,2798421907,AttemptSaved,8517,1028704,Santiago Rodriguez,91.300000,37.708000,33,NaN,False,...,"{'x': 0.5360449735449745, 'y': 0.1936507926984...",False,True,800702.0,Santiago,Rodriguez,Santiago Rodriguez,#181818,Botafogo,h
9,2798422359,Miss,8517,657969,Alexander Barboza,70.884951,37.660000,34,NaN,False,...,"{'x': 0.43102956755225275, 'y': 0.677248677248...",False,False,NaN,Alexander,Barboza,Alexander Barboza,#181818,Botafogo,h

In [54]:
# DF to CSV
df_shots.to_csv('/home/axel/Code/Python/axel/streamlit/csv/CerroBolivar.csv', index=False)

Check concat file

In [2]:
shots = pd.read_csv('/home/axel/Code/Python/axel/streamlit/concat_files/concat_shots.csv')

Most shots

In [78]:
shots['teamName'].value_counts().sort_values(ascending=False)

# teams_df = shots['teamName'].value_counts().reset_index()
# teams_df.columns = ['teamName', 'count']
# teams_df.sort_values(by='count', ascending=False)

teamName
Racing Club                              24
Atlético Nacional                        22
Bahia                                    21
Palmeiras                                19
Vélez Sarsfield                          19
Cerro Porteño                            19
Talleres de Córdoba                      17
Central Córdoba (Santiago del Estero)    17
Barcelona de Guayaquil                   17
Alianza Lima                             16
Olimpia                                  15
Fortaleza EC                             14
Sporting Cristal                         14
Estudiantes de La Plata                  14
San Antonio Bulo Bulo                    14
Flamengo                                 12
Atlético Bucaramanga                     12
Nacional                                 11
Libertad                                 11
Bolívar                                  10
River Plate                              10
Independiente del Valle                  10
Colo-Colo                                 9
Internacional                             8
Botafogo                                  7
Universitario de Deportes                 6
Carabobo FC                               6
Deportivo Táchira                         6
Universidad de Chile                      6
São Paulo                                 5
LDU Quito                                 5
Peñarol                                   4
Name: count, dtype: int64

Filter by shots on target

In [39]:
target_shots = shots[shots['isOnTarget'] == True]
target_shots.shape

(238, 31)

In [54]:
target_shots.groupby('teamName')['isOnTarget'].count().reset_index(name='count').sort_values(by='count', ascending=False).reset_index(drop=True)

                                 teamName  count
0                             Racing Club     16
1                       Atlético Nacional     14
2                         Vélez Sarsfield     12
3                  Barcelona de Guayaquil     12
4                                   Bahia     11
5                               Palmeiras     11
6   Central Córdoba (Santiago del Estero)     10
7                            Alianza Lima     10
8                        Sporting Cristal     10
9                     Talleres de Córdoba     10
10                  San Antonio Bulo Bulo      9
11                                Olimpia      9
12                           Fortaleza EC      9
13                               Nacional      8
14                          Cerro Porteño      8
15                   Atlético Bucaramanga      7
16                          Internacional      7
17                Estudiantes de La Plata      7
18                               Flamengo      6
19                               Libertad      6
20                               Botafogo      6
21                                Bolívar      6
22                              Colo-Colo      6
23                            River Plate      5
24              Universitario de Deportes      4
25                              São Paulo      4
26                            Carabobo FC      4
27                Independiente del Valle      3
28                   Universidad de Chile      3
29                      Deportivo Táchira      2
30                              LDU Quito      2
31                                Peñarol      1

In [3]:
shots.columns

Index(['id', 'eventType', 'teamId', 'playerId', 'playerName', 'x', 'y', 'min',
       'minAdded', 'isBlocked', 'isOnTarget', 'blockedX', 'blockedY',
       'goalCrossedY', 'goalCrossedZ', 'expectedGoals',
       'expectedGoalsOnTarget', 'shotType', 'situation', 'period', 'isOwnGoal',
       'onGoalShot', 'isSavedOffLine', 'isFromInsideBox', 'keeperId',
       'firstName', 'lastName', 'fullName', 'teamColor', 'teamName',
       'source_file'],
      dtype='object')